"""
Tests for Octopus edge/WAF (CloudFront) 403 handling.

A CloudFront "Request blocked" 403 is a rate-limit/WAF response, not an
authentication failure. Treating it as an auth failure makes Predbat discard a
perfectly valid Kraken token and immediately re-mint it; the mint endpoint is
itself blocked, so the component can never recover without a restart.
"""

import asyncio
from unittest.mock import AsyncMock, MagicMock
from octopus import OctopusAPI, integration_context_header, EDGE_BLOCK_REFRESH_AFTER

CLOUDFRONT_403_BODY = (
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n'
    "<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>\n"
    "<BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2>\n"
    "Request blocked.\nGenerated by cloudfront (CloudFront)\n</BODY></HTML>"
)


def _make_response(status, body):
    """Build a mock aiohttp response whose text() returns body."""
    response = MagicMock()
    response.status = status
    response.text = AsyncMock(return_value=body)
    response.request_info = MagicMock()
    response.request_info.headers = {integration_context_header: "test-context"}
    response.__aenter__ = AsyncMock(return_value=response)
    response.__aexit__ = AsyncMock(return_value=None)
    return response


def _make_api(my_predbat, response):
    """Build an OctopusAPI whose POSTs return the given response."""
    api = OctopusAPI(my_predbat, key="test-api-key", account_id="test-account", automatic=False)
    session = MagicMock()
    session.post = MagicMock(return_value=response)
    api.api.async_create_client_session = AsyncMock(return_value=session)
    return api


def test_octopus_waf_block_wrapper(my_predbat):
    return asyncio.run(test_octopus_waf_block(my_predbat))


async def test_octopus_waf_block(my_predbat):
    """
    Tests:
    - Test 1: CloudFront 403 must not discard a valid token or trigger a re-mint
    - Test 2: A genuine 401 must still force a token refresh (existing behaviour)
    - Test 3: An HTTP error response must not be re-read OCTOPUS_MAX_RETRIES times
    """
    print("**** Running Octopus WAF/CloudFront 403 tests ****")
    failed = False

    # Test 1: CloudFront 403 must NOT clear the token nor re-mint it
    print("\n*** Test 1: CloudFront 403 does not discard the token ***")
    api = _make_api(my_predbat, _make_response(403, CLOUDFRONT_403_BODY))
    api.graphql_token = "existing-valid-token"
    api.async_refresh_token = AsyncMock(return_value="should-not-be-called")

    result = await api.async_graphql_query("query { test }", "test-query")

    if result is not None:
        print("ERROR: Expected None from a blocked request, got {}".format(result))
        failed = True
    # One call is the normal cached-token lookup at the top of async_graphql_query.
    # A second call is the forced re-mint that causes the lockout.
    if api.async_refresh_token.call_count != 1:
        print("ERROR: Expected 1 token lookup, got {} - the extra call is the re-mint storm".format(api.async_refresh_token.call_count))
        failed = True
    if api.graphql_token != "existing-valid-token":
        print("ERROR: Valid token was discarded on a CloudFront 403, got {}".format(api.graphql_token))
        failed = True
    if not failed:
        print("PASS: CloudFront 403 left the token intact and did not re-mint")

    # Test 2: a genuine 401 must still refresh the token (do not regress existing behaviour)
    print("\n*** Test 2: genuine 401 still forces a token refresh ***")
    api2 = _make_api(my_predbat, _make_response(401, '{"errors":[{"message":"Unauthorized"}]}'))
    api2.graphql_token = "stale-token"
    api2.async_refresh_token = AsyncMock(return_value=None)

    await api2.async_graphql_query("query { test }", "test-query")

    if not api2.async_refresh_token.called:
        print("ERROR: async_refresh_token was NOT called for a genuine 401")
        failed = True
    else:
        print("PASS: genuine 401 still triggers a token refresh")

    # Test 2b: a genuine JSON 403 from Kraken must still refresh the token, even when its
    # message happens to contain wording that also appears on WAF pages. Misclassifying it
    # would keep an invalid token forever - the same permanent lockout, from the other side.
    print("\n*** Test 2b: JSON 403 mentioning 'access denied' still refreshes ***")
    api2b = _make_api(my_predbat, _make_response(403, '{"errors":[{"message":"Access denied for this account"}]}'))
    api2b.graphql_token = "stale-token"
    # Must return a token so the query proceeds to the POST and reaches the 403 handling
    api2b.async_refresh_token = AsyncMock(return_value="fresh-token")

    await api2b.async_graphql_query("query { test }", "test-query")

    if api2b.async_refresh_token.call_count < 2:
        print("ERROR: a genuine JSON 403 was misclassified as a CDN block, so the token was never refreshed")
        failed = True
    else:
        print("PASS: JSON 403 treated as a real auth failure and refreshed")

    # Test 3: an HTTP error response must not be re-read repeatedly.
    # aiohttp caches the body, so re-reading the same response can never change
    # the outcome - it only duplicates logs and sleeps.
    print("\n*** Test 3: HTTP error responses are not re-read repeatedly ***")
    api3 = OctopusAPI(my_predbat, key="test-api-key", account_id="test-account", automatic=False)
    response3 = _make_response(403, CLOUDFRONT_403_BODY)

    call_count = {"n": 0}
    real_read = api3.async_read_response

    async def counting_read(resp, url, ignore_errors=False):
        """Count reads of the response before delegating to the real implementation."""
        call_count["n"] += 1
        return await real_read(resp, url, ignore_errors=ignore_errors)

    api3.async_read_response = counting_read

    result3 = await api3.async_read_response_retry(response3, "https://api.octopus.energy/v1/graphql/")

    if result3 is not None:
        print("ERROR: Expected None for a blocked response, got {}".format(result3))
        failed = True
    if call_count["n"] != 1:
        print("ERROR: Response was read {} times; a definitive HTTP error must be read once".format(call_count["n"]))
        failed = True
    else:
        print("PASS: HTTP error response was read exactly once")

    # Test 4: persistent edge blocks must eventually force a refresh anyway. A generic
    # "403 Forbidden" HTML page is indistinguishable from a WAF page, so if a genuinely
    # revoked credential ever produced one, never refreshing would lock the component out
    # permanently - the very failure the HTTP 401/403 refresh path was added to fix.
    print("\n*** Test 4: persistent edge blocks eventually force a refresh ***")
    api4 = _make_api(my_predbat, _make_response(403, "<html><head><title>403 Forbidden</title></head><body></body></html>"))
    api4.graphql_token = "token"
    api4.async_refresh_token = AsyncMock(return_value="token")

    queries = EDGE_BLOCK_REFRESH_AFTER + 1
    for _ in range(queries):
        await api4.async_graphql_query("query { test }", "test-query")

    # Without an escape hatch there is exactly one refresh lookup per query and never more
    if api4.async_refresh_token.call_count <= queries:
        print("ERROR: {} consecutive edge blocks never forced a refresh - component can lock out permanently".format(queries))
        failed = True
    else:
        print("PASS: persistent edge blocks forced a token refresh")

    # Test 5: callers that pass ignore_errors=True treat the lookup as optional, so an edge
    # block must not inflate failures_total or emit warnings for them.
    print("\n*** Test 5: edge block respects ignore_errors ***")
    api5 = _make_api(my_predbat, _make_response(403, CLOUDFRONT_403_BODY))
    api5.graphql_token = "token"
    api5.async_refresh_token = AsyncMock(return_value="token")
    api5.failures_total = 0

    await api5.async_graphql_query("query { test }", "test-query", ignore_errors=True)

    if api5.failures_total != 0:
        print("ERROR: edge block incremented failures_total despite ignore_errors=True, got {}".format(api5.failures_total))
        failed = True
    else:
        print("PASS: edge block honoured ignore_errors")

    if failed:
        print("**** Octopus WAF/CloudFront 403 tests FAILED ****")
    else:
        print("**** All Octopus WAF/CloudFront 403 tests PASSED ****")
    return failed
