# These are supported funding model platforms

github: springfall2008
custom: ['https://paypal.me/predbat?country.x=GB&locale.x=en_GB', 'https://share.octopus.energy/jolly-eel-176', 'https://vpp.axle.energy/landing/grid?ref=R-VWIICRSA']
