import { useEffect, useMemo, useRef, useState } from 'react'
import {
  Chart,
  Filler,
  Legend,
  LinearScale,
  LineController,
  LineElement,
  PointElement,
  Tooltip,
  type ChartConfiguration,
  type ChartDataset,
  type Plugin
} from 'chart.js'

import type { SolarChartData } from '../types/charts'
import { useStoredState } from '../hooks/useStoredState'
import { pointsInWindow, toChartPoints, type ChartPoint } from '../utils/batteryChart'
import { combineSolarForecast, getSolarChartWindow, getSolarPowerWindow, peakSolarPower, solarAccuracy, sumDailyCumulative } from '../utils/solarChart'

import './BatteryChart.css'

Chart.register(LineController, LineElement, PointElement, LinearScale, Filler, Tooltip, Legend)

type SolarChartProps = {
  data: SolarChartData
}

type ComparisonKey = 'raw' | 'range'
type SolarView = 'power' | 'accuracy'

type SolarLegendItem = {
  key: string
  label: string
  colour: string
  description: string
}

const legendItems: SolarLegendItem[] = [
  {
    key: 'actual',
    label: 'Actual generation',
    colour: 'var(--color-flow-solar)',
    description: 'The solar power your inverter measured. Historical readings stop at Now.'
  },
  {
    key: 'calibrated',
    label: 'Calibrated forecast',
    colour: 'var(--color-current)',
    description: 'Predbat’s forecast adjusted using recent differences between predicted and measured solar generation.'
  },
  {
    key: 'raw',
    label: 'Original forecast',
    colour: '#64748b',
    description: 'The solar provider forecast before Predbat applies its local calibration.'
  },
  {
    key: 'low',
    label: 'Lower estimate',
    colour: '#a855f7',
    description: 'Predbat’s conservative solar scenario, derived from recent lower-generation days.'
  },
  {
    key: 'high',
    label: 'Upper estimate',
    colour: '#16a34a',
    description: 'Predbat’s optimistic solar scenario, derived from recent higher-generation days.'
  }
]

const accuracyLegendItems: SolarLegendItem[] = [
  {
    key: 'energy_actual',
    label: 'Actual energy',
    colour: 'var(--color-flow-solar)',
    description: 'Cumulative solar energy generated since midnight on each day.'
  },
  {
    key: 'energy_forecast',
    label: 'Forecast energy',
    colour: 'var(--color-current)',
    description: 'Cumulative calibrated solar energy Predbat expected to have generated by that time.'
  }
]

function SolarLegend({ item }: { item: SolarLegendItem }) {
  return (
    <span className="battery-chart-legend-item" tabIndex={0}>
      <span
        className="battery-chart-legend-marker"
        style={{ '--battery-chart-legend-colour': item.colour } as React.CSSProperties}
        aria-hidden="true"
      />
      <span>{item.label}</span>
      <span className="battery-chart-help-popup" role="tooltip">{item.description}</span>
    </span>
  )
}

function latestValueAt(points: ChartPoint[], at: number): number | null {
  return points.reduce<number | null>((latest, point) => point.x <= at ? point.y : latest, null)
}

function formatPower(value: number | null): string {
  return value === null ? '—' : `${value.toFixed(2)} kW`
}

function formatEnergy(value: number | null): string {
  return value === null ? '—' : `${value.toFixed(2)} kWh`
}

function formatDifference(value: number | null): string {
  if (value === null) return '—'
  return `${value > 0 ? '+' : ''}${value.toFixed(2)} kWh`
}

function formatPercentage(value: number | null): string {
  return value === null ? '—' : `${value.toFixed(0)}%`
}

function makeSolarOverlayPlugin(now: number, nowColour: string): Plugin<'line'> {
  return {
    id: 'predbat-solar-overlays',
    beforeDatasetsDraw(chart) {
      const { ctx, chartArea, scales } = chart
      const nowPixel = scales.x.getPixelForValue(now)

      ctx.save()
      ctx.fillStyle = 'rgba(15, 23, 42, 0.07)'
      ctx.fillRect(chartArea.left, chartArea.top, Math.max(0, nowPixel - chartArea.left), chartArea.bottom - chartArea.top)
      ctx.restore()
    },
    afterDatasetsDraw(chart) {
      const { ctx, chartArea, scales } = chart
      const nowPixel = scales.x.getPixelForValue(now)

      ctx.save()
      ctx.strokeStyle = nowColour
      ctx.lineWidth = 1.5
      ctx.setLineDash([5, 4])
      ctx.beginPath()
      ctx.moveTo(nowPixel, chartArea.top)
      ctx.lineTo(nowPixel, chartArea.bottom)
      ctx.stroke()
      ctx.setLineDash([])
      ctx.fillStyle = nowColour
      ctx.font = '600 11px sans-serif'
      ctx.fillText('Now', nowPixel + 5, chartArea.top + 13)
      ctx.restore()
    }
  }
}

/** Render measured solar power and Predbat's current and historical forecasts. */
export default function SolarChart({ data }: SolarChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [view, setView] = useStoredState<SolarView>('predbat-chart-solar-view', 'power', ['power', 'accuracy'])
  const [powerDays, setPowerDays] = useStoredState<number>('predbat-chart-solar-power-range', 1, [1, 3, 7])
  const [accuracyDays, setAccuracyDays] = useStoredState<number>('predbat-chart-solar-accuracy-range', 7, [1, 3, 7])
  const [comparisons, setComparisons] = useState<Set<ComparisonKey>>(new Set(['raw', 'range']))
  const [themeRevision, setThemeRevision] = useState(0)
  const days = view === 'power' ? powerDays : accuracyDays
  const generatedAt = Date.parse(data.generated_at)
  const allPoints = useMemo(() => ({
    actual: toChartPoints(data.series.actual),
    forecastHistory: toChartPoints(data.series.forecast_history),
    calibratedHistory: toChartPoints(data.series.forecast_history_calibrated),
    forecast: toChartPoints(data.series.forecast),
    low: toChartPoints(data.series.forecast_low),
    high: toChartPoints(data.series.forecast_high),
    calibrated: toChartPoints(data.series.forecast_calibrated),
    energyActual: toChartPoints(data.series.energy_actual),
    energyForecast: toChartPoints(data.series.energy_forecast)
  }), [data.series])
  const forecastEnd = useMemo(
    () => Math.max(...allPoints.forecast.map((point) => point.x)),
    [allPoints.forecast]
  )
  const powerWindow = useMemo(
    () => getSolarPowerWindow(data.generated_at, powerDays, forecastEnd),
    [data.generated_at, forecastEnd, powerDays]
  )
  const window = useMemo(
    () => view === 'power' ? powerWindow : getSolarChartWindow(data.generated_at, days),
    [data.generated_at, days, powerWindow, view]
  )
  const actualPoints = pointsInWindow(allPoints.actual, window)
  const calibratedPoints = pointsInWindow(
    combineSolarForecast(allPoints.calibratedHistory, allPoints.calibrated, generatedAt),
    window
  )
  const rawPoints = pointsInWindow(
    combineSolarForecast(allPoints.forecastHistory, allPoints.forecast, generatedAt),
    window
  )
  const lowPoints = pointsInWindow(allPoints.low, window)
  const highPoints = pointsInWindow(allPoints.high, window)
  const energyActualPoints = pointsInWindow(allPoints.energyActual, window)
  const energyForecastPoints = pointsInWindow(allPoints.energyForecast, window)
  const currentActual = latestValueAt(allPoints.actual, generatedAt)
  const currentForecast = latestValueAt(allPoints.calibrated, generatedAt)
  const energyActualInView = sumDailyCumulative(energyActualPoints)
  const energyForecastInView = sumDailyCumulative(energyForecastPoints)
  const accuracy = solarAccuracy(energyActualInView, energyForecastInView)
  const comparisonAvailability: Record<ComparisonKey, boolean> = {
    raw: rawPoints.length > 0,
    range: lowPoints.length > 0 || highPoints.length > 0
  }

  function setRangeDays(rangeDays: number) {
    if (view === 'power') {
      setPowerDays(rangeDays)
    } else {
      setAccuracyDays(rangeDays)
    }
  }

  useEffect(() => {
    const observer = new MutationObserver(() => setThemeRevision((revision) => revision + 1))
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] })
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!canvasRef.current) {
      return
    }

    const styles = getComputedStyle(document.documentElement)
    const textColour = styles.getPropertyValue('--color-text-secondary').trim() || '#4b5563'
    const gridColour = styles.getPropertyValue('--color-border').trim() || '#e5e7eb'
    const actualColour = styles.getPropertyValue('--color-flow-solar').trim() || '#f59e0b'
    const forecastColour = styles.getPropertyValue('--color-current').trim() || '#2563eb'
    const nowColour = styles.getPropertyValue('--color-warning').trim() || '#f59e0b'
    const datasets: ChartDataset<'line', ChartPoint[]>[] = view === 'accuracy'
      ? [
          {
            label: 'Actual energy',
            data: energyActualPoints,
            borderColor: actualColour,
            backgroundColor: actualColour,
            borderWidth: 3,
            pointRadius: 0,
            tension: 0.2
          },
          {
            label: 'Forecast energy',
            data: energyForecastPoints,
            borderColor: forecastColour,
            backgroundColor: forecastColour,
            borderWidth: 3,
            borderDash: [6, 4],
            pointRadius: 0,
            tension: 0.2
          }
        ]
      : [
          {
            label: 'Actual generation',
            data: actualPoints,
            borderColor: actualColour,
            backgroundColor: actualColour,
            borderWidth: 3,
            pointRadius: 0,
            tension: 0.2
          },
          {
            label: 'Calibrated forecast',
            data: calibratedPoints,
            borderColor: forecastColour,
            backgroundColor: forecastColour,
            borderWidth: 3,
            pointRadius: 0,
            tension: 0.2
          }
        ]

    if (view === 'power' && comparisons.has('raw') && comparisonAvailability.raw) {
      datasets.push({
        label: 'Original forecast',
        data: rawPoints,
        borderColor: '#64748b',
        backgroundColor: '#64748b',
        borderWidth: 1.5,
        borderDash: [6, 4],
        pointRadius: 0,
        tension: 0.2
      })
    }
    if (view === 'power' && comparisons.has('range') && comparisonAvailability.range) {
      datasets.push(
        {
          label: 'Lower estimate',
          data: lowPoints,
          borderColor: '#a855f7',
          backgroundColor: '#a855f7',
          borderWidth: 1.5,
          borderDash: [3, 4],
          pointRadius: 0,
          tension: 0.2
        },
        {
          label: 'Upper estimate',
          data: highPoints,
          borderColor: '#16a34a',
          backgroundColor: '#16a34a',
          borderWidth: 1.5,
          borderDash: [3, 4],
          pointRadius: 0,
          tension: 0.2
        }
      )
    }

    const configuration: ChartConfiguration<'line', ChartPoint[]> = {
      type: 'line',
      data: { datasets },
      plugins: [makeSolarOverlayPlugin(generatedAt, nowColour)],
      options: {
        animation: false,
        responsive: true,
        maintainAspectRatio: false,
        parsing: false,
        normalized: true,
        interaction: { intersect: false, mode: 'nearest' },
        scales: {
          x: {
            type: 'linear',
            min: window.start,
            max: window.end,
            grid: { color: gridColour },
            ticks: {
              color: textColour,
              maxTicksLimit: days === 1 ? 9 : 8,
              callback(value) {
                return new Intl.DateTimeFormat(undefined, days === 1
                  ? { hour: '2-digit', minute: '2-digit' }
                  : { weekday: 'short', day: 'numeric', hour: '2-digit' }
                ).format(Number(value))
              }
            }
          },
          y: {
            beginAtZero: true,
            grid: { color: gridColour },
            ticks: { color: textColour, callback: (value) => `${value} ${view === 'accuracy' ? 'kWh' : 'kW'}` }
          }
        },
        plugins: {
          legend: { display: false },
          tooltip: {
            callbacks: {
              title(items) {
                return new Intl.DateTimeFormat(undefined, {
                  weekday: 'short',
                  day: 'numeric',
                  month: 'short',
                  hour: '2-digit',
                  minute: '2-digit'
                }).format(Number(items[0]?.parsed.x))
              },
              label(item) {
                return `${item.dataset.label}: ${Number(item.parsed.y).toFixed(2)} ${view === 'accuracy' ? 'kWh' : 'kW'}`
              }
            }
          }
        }
      }
    }

    const chart = new Chart(canvasRef.current, configuration)
    return () => chart.destroy()
  }, [actualPoints, calibratedPoints, comparisonAvailability.range, comparisonAvailability.raw, comparisons, days, energyActualPoints, energyForecastPoints, generatedAt, highPoints, lowPoints, rawPoints, themeRevision, view, window])

  function toggleComparison(key: ComparisonKey) {
    setComparisons((current) => {
      const next = new Set(current)
      if (next.has(key)) {
        next.delete(key)
      } else {
        next.add(key)
      }
      return next
    })
  }

  const visibleLegendItems = view === 'accuracy'
    ? accuracyLegendItems
    : legendItems.filter(({ key }) => {
        if (key === 'raw') return comparisons.has('raw') && comparisonAvailability.raw
        if (key === 'low' || key === 'high') return comparisons.has('range') && comparisonAvailability.range
        return true
      })

  return (
    <section className="battery-chart-card" aria-labelledby="solar-chart-heading">
      <div className="battery-chart-header">
        <div>
          <h2 id="solar-chart-heading">{view === 'power' ? 'Solar power forecast' : 'Solar forecast accuracy'}</h2>
          <p>{view === 'power'
            ? 'Predbat’s future solar scenarios, with measured inverter output for context.'
            : 'Historical cumulative forecast energy compared with the energy actually generated.'}</p>
        </div>

        <div className="solar-chart-controls">
          <div className="battery-chart-range" aria-label="Solar measurement">
            <button type="button" className={view === 'power' ? 'is-active' : ''} aria-pressed={view === 'power'} onClick={() => setView('power')}>Forecast power</button>
            <button type="button" className={view === 'accuracy' ? 'is-active' : ''} aria-pressed={view === 'accuracy'} onClick={() => setView('accuracy')}>Energy accuracy</button>
          </div>
          <div className="battery-chart-range" aria-label="Solar chart range">
            {[1, 3, 7].map((rangeDays) => (
              <button
                type="button"
                className={days === rangeDays ? 'is-active' : ''}
                aria-pressed={days === rangeDays}
                onClick={() => setRangeDays(rangeDays)}
                key={rangeDays}
              >
                {rangeDays}d
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="battery-chart-summary">
        {view === 'power' ? (
          <>
            <div><span>Generating now</span><strong>{formatPower(currentActual)}</strong></div>
            <div><span>Forecast now</span><strong>{formatPower(currentForecast)}</strong></div>
            <div><span>Actual peak in view</span><strong>{formatPower(peakSolarPower(actualPoints))}</strong></div>
            <div><span>Forecast peak in view</span><strong>{formatPower(peakSolarPower(calibratedPoints))}</strong></div>
          </>
        ) : (
          <>
            <div><span>Generated in view</span><strong>{formatEnergy(energyActualInView)}</strong></div>
            <div><span>Forecast in view</span><strong>{formatEnergy(energyForecastInView)}</strong></div>
            <div><span>Difference in view</span><strong>{formatDifference(accuracy.difference)}</strong></div>
            <div>
              <span className="battery-chart-summary-help" tabIndex={0}>
                Forecast achieved in view
                <span className="battery-chart-help-popup" role="tooltip">Total actual energy in the selected days as a percentage of the total calibrated forecast for the same period.</span>
              </span>
              <strong>{formatPercentage(accuracy.achieved)}</strong>
            </div>
          </>
        )}
      </div>

      {view === 'power' && days > 1 && powerWindow.forecastDays < days && (
        <p className="solar-chart-availability" role="status">
          {powerWindow.forecastDays === 0
            ? 'No forecast days are currently available.'
            : `Only ${powerWindow.forecastDays} ${powerWindow.forecastDays === 1 ? 'day' : 'days'} of forecast data ${powerWindow.forecastDays === 1 ? 'is' : 'are'} available.`}
          {' '}Historical data fills the remaining {days - powerWindow.forecastDays} {days - powerWindow.forecastDays === 1 ? 'day' : 'days'}.
        </p>
      )}

      <div className="battery-chart-legend" aria-label="Chart series">
        {visibleLegendItems.map((item) => <SolarLegend item={item} key={item.key} />)}
      </div>

      <div className="battery-chart-canvas">
        <canvas ref={canvasRef} role="img" aria-label={view === 'power' ? 'Measured and forecast solar power' : 'Actual and forecast cumulative solar energy'} />
      </div>

      {view === 'power' && <details className="battery-chart-comparisons">
        <summary>Compare forecast scenarios</summary>
        <div>
          <label className={comparisonAvailability.raw ? '' : 'is-unavailable'} title={comparisonAvailability.raw ? legendItems[2].description : 'No original forecast data in this range'}>
            <input type="checkbox" checked={comparisons.has('raw')} disabled={!comparisonAvailability.raw} onChange={() => toggleComparison('raw')} />
            <span>Original forecast</span>
            {!comparisonAvailability.raw && <small>No data in this range</small>}
          </label>
          <label className={comparisonAvailability.range ? '' : 'is-unavailable'} title={comparisonAvailability.range ? 'Show the lower and upper solar estimates.' : 'No forecast range data in this range'}>
            <input type="checkbox" checked={comparisons.has('range')} disabled={!comparisonAvailability.range} onChange={() => toggleComparison('range')} />
            <span>Lower and upper estimates</span>
            {!comparisonAvailability.range && <small>No data in this range</small>}
          </label>
        </div>
      </details>}
    </section>
  )
}
