# -----------------------------------------------------------------------------
# Predbat Home Battery System
# Copyright Trefor Southwell 2024 - All Rights Reserved
# This application maybe used for personal use only and not for commercial use
# -----------------------------------------------------------------------------
# fmt off
# pylint: disable=consider-using-f-string
# pylint: disable=line-too-long
# pylint: disable=attribute-defined-outside-init

from datetime import datetime, timedelta
from predbat import THIS_VERSION


TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
TIME_FORMAT_SECONDS = "%Y-%m-%dT%H:%M:%S.%f%z"
TIME_FORMAT_SOLCAST = "%Y-%m-%dT%H:%M:%S.%f0%z"  # 2024-05-31T18:00:00.0000000Z
TIME_FORMAT_OCTOPUS = "%Y-%m-%d %H:%M:%S%z"
TIME_FORMAT_SOLIS = "%Y-%m-%d %H:%M:%S"
PREDICT_STEP = 5
RUN_EVERY = 5
CONFIG_ROOTS = ["/config", "/conf", "/homeassistant", "./"]
TIME_FORMAT_HA = "%Y-%m-%dT%H:%M:%S%z"
TIMEOUT = 60 * 5
CONFIG_REFRESH_PERIOD = 60 * 8

# 240v x 100 amps x 3 phases / 1000 to kW / 60 minutes in an hour is the maximum kWh in a 1 minute period
MAX_INCREMENT = 240 * 100 * 3 / 1000 / 60
MINUTE_WATT = 60 * 1000

INVERTER_TEST = False  # Run inverter control self test

# Create an array of times in the day in 5-minute intervals
BASE_TIME = datetime.strptime("00:00:00", "%H:%M:%S")
OPTIONS_TIME = [((BASE_TIME + timedelta(seconds=minute * 60)).strftime("%H:%M:%S")) for minute in range(0, 24 * 60, 5)]

# Inverter modes
PREDBAT_MODE_OPTIONS = ["Monitor", "Control SOC only", "Control charge", "Control charge & discharge"]
PREDBAT_MODE_MONITOR = 0
PREDBAT_MODE_CONTROL_SOC = 1
PREDBAT_MODE_CONTROL_CHARGE = 2
PREDBAT_MODE_CONTROL_CHARGEDISCHARGE = 3

# Predbat update options
PREDBAT_UPDATE_OPTIONS = [f"{THIS_VERSION} Loading..."]
PREDBAT_SAVE_RESTORE = ["save current", "restore default"]

# Configuration options inside HA
CONFIG_ITEMS = [
    {
        "name": "version",
        "friendly_name": "Predbat Core Update",
        "type": "update",
        "title": "Predbat",
        "installed_version": THIS_VERSION,
        "release_url": f"https://github.com/springfall2008/batpred/releases/tag/{THIS_VERSION}",
        "entity_picture": "https://user-images.githubusercontent.com/48591903/249456079-e98a0720-d2cf-4b71-94ab-97fe09b3cee1.png",
        "restore": False,
        "default": False,
    },
    {
        "name": "expert_mode",
        "friendly_name": "Expert Mode",
        "type": "switch",
        "default": False,
    },
    {
        "name": "active",
        "friendly_name": "Predbat Active",
        "type": "switch",
        "default": False,
        "restore": False,
    },
    {
        "name": "compare_active",
        "friendly_name": "Predbat Compare Active",
        "type": "switch",
        "default": False,
        "restore": False,
    },
    {
        "name": "pv_metric10_weight",
        "friendly_name": "Metric 10 Weight",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 0.15,
    },
    {
        "name": "pv_scaling",
        "friendly_name": "PV Scaling",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.0,
    },
    {
        "name": "load_scaling",
        "friendly_name": "Load Scaling",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.05,
    },
    {
        "name": "load_scaling10",
        "friendly_name": "Load Scaling PV10%",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.1,
    },
    {
        "name": "load_scaling_saving",
        "friendly_name": "Load Scaling for saving sessions",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.1,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.0,
    },
    {
        "name": "load_scaling_free",
        "friendly_name": "Load Scaling for free sessions",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.1,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.2,
    },
    {
        "name": "battery_rate_max_scaling",
        "friendly_name": "Battery rate max scaling charge",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.0,
    },
    {
        "name": "battery_rate_max_scaling_discharge",
        "friendly_name": "Battery rate max scaling discharge",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.0,
    },
    {
        "name": "battery_loss",
        "friendly_name": "Battery loss charge ",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:call-split",
        "default": 0.03,
    },
    {
        "name": "battery_loss_discharge",
        "friendly_name": "Battery loss discharge",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:call-split",
        "default": 0.03,
    },
    {
        "name": "inverter_loss",
        "friendly_name": "Inverter Loss",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:call-split",
        "default": 0.04,
    },
    {
        "name": "inverter_hybrid",
        "friendly_name": "Inverter Hybrid",
        "type": "switch",
        "default": True,
    },
    {
        "name": "inverter_soc_reset",
        "friendly_name": "Inverter SOC Reset",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
    },
    {
        "name": "inverter_set_charge_before",
        "friendly_name": "Inverter Set charge window before start",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
    },
    {
        "name": "battery_capacity_nominal",
        "friendly_name": "Use the Battery Capacity Nominal size",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
    },
    {
        "name": "car_charging_energy_scale",
        "friendly_name": "Car charging energy scale",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 1.0,
    },
    {
        "name": "car_charging_threshold",
        "friendly_name": "Car charging threshold",
        "type": "input_number",
        "min": 4,
        "max": 8.5,
        "step": 0.10,
        "unit": "kW",
        "icon": "mdi:ev-station",
        "default": 6.0,
    },
    {
        "name": "car_charging_rate",
        "friendly_name": "Car charging rate",
        "type": "input_number",
        "min": 1,
        "max": 8.5,
        "step": 0.10,
        "unit": "kW",
        "icon": "mdi:ev-station",
        "default": 7.4,
    },
    {
        "name": "car_charging_loss",
        "friendly_name": "Car charging loss",
        "type": "input_number",
        "min": 0,
        "max": 1.0,
        "step": 0.01,
        "unit": "*",
        "icon": "mdi:call-split",
        "default": 0.08,
    },
    {
        "name": "best_soc_min",
        "friendly_name": "Best SOC Min",
        "type": "input_number",
        "min": 0,
        "max": 30.0,
        "step": 0.10,
        "unit": "kWh",
        "icon": "mdi:battery-50",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "best_soc_max",
        "friendly_name": "Best SOC Max",
        "type": "input_number",
        "min": 0,
        "max": 30.0,
        "step": 0.10,
        "unit": "kWh",
        "icon": "mdi:battery-50",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "best_soc_keep",
        "friendly_name": "Best SOC Keep",
        "type": "input_number",
        "min": 0,
        "max": 30.0,
        "step": 0.10,
        "unit": "kWh",
        "icon": "mdi:battery-50",
        "default": 0.0,
    },
    {
        "name": "best_soc_keep_weight",
        "friendly_name": "Best SOC Keep Weighting",
        "type": "input_number",
        "min": 0.1,
        "max": 5,
        "step": 0.10,
        "unit": "*",
        "icon": "mdi:multiplication",
        "default": 0.5,
        "enable": "expert_mode",
    },
    {
        "name": "metric_min_improvement",
        "friendly_name": "Metric Min Improvement",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "metric_min_improvement_export",
        "oldname": "metric_min_improvement_discharge",
        "friendly_name": "Metric Min Improvement Export",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.1,
    },
    {
        "name": "metric_min_improvement_export_freeze",
        "friendly_name": "Metric Min Improvement Export Freeze",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.1,
    },
    {
        "name": "metric_battery_cycle",
        "friendly_name": "Metric Battery Cycle Cost",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0,
    },
    {
        "name": "metric_battery_value_scaling",
        "friendly_name": "Metric Battery Value Scaling",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.1,
        "unit": "*",
        "icon": "mdi:multiplication",
        "enable": "expert_mode",
        "default": 1.0,
    },
    {
        "name": "metric_future_rate_offset_import",
        "friendly_name": "Metric Future Rate Offset Import",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "metric_future_rate_offset_export",
        "friendly_name": "Metric Future Rate Offset Export",
        "type": "input_number",
        "min": -50,
        "max": 50.0,
        "step": 0.1,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "metric_inday_adjust_damping",
        "friendly_name": "In-day adjustment damping factor",
        "type": "input_number",
        "min": 0.5,
        "max": 2.0,
        "step": 0.05,
        "unit": "*",
        "icon": "mdi:call-split",
        "enable": "expert_mode",
        "default": 0.95,
    },
    {
        "name": "metric_cloud_enable",
        "friendly_name": "Enable Cloud Model",
        "type": "switch",
        "default": True,
        "enable": "expert_mode",
    },
    {
        "name": "metric_load_divergence_enable",
        "friendly_name": "Enable Load Divergence Model",
        "type": "switch",
        "default": True,
        "enable": "expert_mode",
    },
    {
        "name": "metric_self_sufficiency",
        "friendly_name": "Metric Self Sufficiency",
        "type": "input_number",
        "min": 0,
        "max": 100,
        "step": 0.5,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "set_reserve_min",
        "friendly_name": "Set Reserve Min",
        "type": "input_number",
        "min": 0,
        "max": 100,
        "step": 1,
        "unit": "%",
        "icon": "mdi:percent",
        "default": 4.0,
        "reset_inverter": True,
    },
    {
        "name": "rate_low_threshold",
        "friendly_name": "Rate Low Threshold",
        "type": "input_number",
        "min": 0.00,
        "max": 2.00,
        "step": 0.05,
        "unit": "*",
        "icon": "mdi:multiplication",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "rate_high_threshold",
        "friendly_name": "Rate High Threshold",
        "type": "input_number",
        "min": 0.00,
        "max": 2.00,
        "step": 0.05,
        "unit": "*",
        "icon": "mdi:multiplication",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "combine_rate_threshold",
        "friendly_name": "Combine Rate Threshold",
        "type": "input_number",
        "min": 0,
        "max": 5.0,
        "step": 0.1,
        "unit": "p",
        "icon": "mdi:table-merge-cells",
        "enable": "expert_mode",
        "default": 0.0,
    },
    {
        "name": "car_charging_hold",
        "friendly_name": "Car charging hold",
        "type": "switch",
        "default": True,
    },
    {
        "name": "car_charging_manual_soc",
        "friendly_name": "Car charging manual SOC",
        "type": "switch",
        "default": False,
    },
    {
        "name": "car_charging_manual_soc_kwh",
        "friendly_name": "Car manual SOC kWh",
        "type": "input_number",
        "min": 0,
        "max": 100,
        "step": 0.01,
        "unit": "kWh",
        "icon": "mdi:ev-station",
        "enable": "car_charging_manual_soc",
        "default": 0.0,
        "restore": False,
    },
    {
        "name": "octopus_intelligent_charging",
        "friendly_name": "Octopus Intelligent Charging",
        "type": "switch",
        "default": True,
    },
    {
        "name": "octopus_intelligent_ignore_unplugged",
        "friendly_name": "Ignore Intelligent slots when car is unplugged",
        "type": "switch",
        "default": False,
        "enable": "expert_mode",
    },
    {
        "name": "octopus_intelligent_consider_full",
        "friendly_name": "Consider car full as part of Intelligent plan",
        "type": "switch",
        "default": False,
        "enable": "expert_mode",
    },
    {
        "name": "car_charging_plan_smart",
        "friendly_name": "Car Charging Plan Smart",
        "type": "switch",
        "default": False,
    },
    {
        "name": "car_charging_plan_max_price",
        "friendly_name": "Car Charging Plan max price",
        "type": "input_number",
        "min": -99,
        "max": 99,
        "step": 1,
        "unit": "p",
        "icon": "mdi:ev-station",
        "default": 0,
    },
    {
        "name": "car_charging_from_battery",
        "friendly_name": "Allow car to charge from battery",
        "type": "switch",
        "default": False,
        "reset_inverter": True,
    },
    {
        "name": "calculate_export_oncharge",
        "oldname": "calculate_discharge_oncharge",
        "friendly_name": "Calculate Export within charge slots",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
    },
    {
        "name": "calculate_second_pass",
        "friendly_name": "Calculate full second pass (slower)",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
    },
    {
        "name": "calculate_tweak_plan",
        "friendly_name": "Calculate tweak second pass",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
    },
    {
        "name": "calculate_import_low_export",
        "friendly_name": "Calculate import slots on low export rate slots first",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
        "oldname": "calculate_secondary_order_slots",
    },
    {
        "name": "calculate_export_high_import",
        "friendly_name": "Calculate export slots on high import rate slots first",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
    },
    {
        "name": "calculate_inday_adjustment",
        "friendly_name": "Calculate in-day adjustment",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
    },
    {
        "name": "calculate_plan_every",
        "friendly_name": "Calculate plan every N minutes",
        "type": "input_number",
        "min": 5,
        "max": 60,
        "step": 5,
        "unit": "minutes",
        "icon": "mdi:clock-end",
        "enable": "expert_mode",
        "default": 10,
    },
    {
        "name": "combine_charge_slots",
        "friendly_name": "Combine Charge Slots",
        "type": "switch",
        "default": False,
    },
    {
        "name": "combine_export_slots",
        "oldname": "combine_discharge_slots",
        "friendly_name": "Combine Export Slots",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
    },
    {
        "name": "set_status_notify",
        "friendly_name": "Set Status Notify",
        "type": "switch",
        "default": True,
    },
    {
        "name": "set_inverter_notify",
        "friendly_name": "Set Inverter Notify",
        "type": "switch",
        "default": False,
    },
    {
        "name": "set_charge_freeze",
        "friendly_name": "Set Charge Freeze",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
        "reset_inverter": True,
    },
    {
        "name": "set_charge_low_power",
        "friendly_name": "Set Charge Low Power Mode",
        "type": "switch",
        "default": False,
        "reset_inverter": True,
    },
    {
        "name": "set_export_low_power",
        "friendly_name": "Set Export Low Power Mode",
        "type": "switch",
        "default": False,
        "reset_inverter": True,
    },
    {
        "name": "charge_low_power_margin",
        "friendly_name": "Low power mode margin",
        "type": "input_number",
        "min": 0,
        "max": 30,
        "step": 5,
        "unit": "minutes",
        "icon": "mdi:seatbelt",
        "enable": "set_charge_low_power",
        "default": 10,
    },
    {
        "name": "set_reserve_enable",
        "friendly_name": "Set Reserve Enable",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
        "reset_inverter": True,
    },
    {
        "name": "set_export_freeze",
        "oldname": "set_discharge_freeze",
        "friendly_name": "Set Export Freeze",
        "type": "switch",
        "default": True,
        "reset_inverter": True,
    },
    {
        "name": "set_export_freeze_only",
        "oldname": "set_discharge_freeze_only",
        "friendly_name": "Set Export Freeze Only",
        "type": "switch",
        "enable": "expert_mode",
        "default": False,
        "reset_inverter": True,
    },
    {
        "name": "set_discharge_during_charge",
        "friendly_name": "Set discharge During Charge",
        "type": "switch",
        "default": True,
    },
    {
        "name": "set_read_only",
        "friendly_name": "Read Only mode",
        "type": "switch",
        "default": False,
        "reset_inverter_force": True,
    },
    {
        "name": "balance_inverters_enable",
        "friendly_name": "Balance Inverters Enable (Beta)",
        "type": "switch",
        "default": False,
    },
    {
        "name": "balance_inverters_charge",
        "friendly_name": "Balance Inverters for charging",
        "type": "switch",
        "enable": "balance_inverters_enable",
        "default": True,
    },
    {
        "name": "balance_inverters_discharge",
        "friendly_name": "Balance Inverters for discharge",
        "type": "switch",
        "enable": "balance_inverters_enable",
        "default": True,
    },
    {
        "name": "balance_inverters_crosscharge",
        "friendly_name": "Balance Inverters for cross-charging",
        "type": "switch",
        "enable": "balance_inverters_enable",
        "default": True,
    },
    {
        "name": "balance_inverters_threshold_charge",
        "friendly_name": "Balance Inverters threshold charge",
        "type": "input_number",
        "min": 1,
        "max": 20,
        "step": 1,
        "unit": "%",
        "icon": "mdi:percent",
        "enable": "balance_inverters_enable",
        "default": 1.0,
    },
    {
        "name": "balance_inverters_threshold_discharge",
        "friendly_name": "Balance Inverters threshold discharge",
        "type": "input_number",
        "min": 1,
        "max": 20,
        "step": 1,
        "unit": "%",
        "icon": "mdi:percent",
        "enable": "balance_inverters_enable",
        "default": 1.0,
    },
    {
        "name": "debug_enable",
        "friendly_name": "Debug Enable",
        "type": "switch",
        "icon": "mdi:bug-outline",
        "default": False,
    },
    {
        "name": "car_charging_plan_time",
        "friendly_name": "Car charging planned ready time",
        "type": "select",
        "options": OPTIONS_TIME,
        "icon": "mdi:clock-end",
        "default": "07:00:00",
    },
    {
        "name": "mode",
        "friendly_name": "Predbat mode",
        "type": "select",
        "options": PREDBAT_MODE_OPTIONS,
        "icon": "mdi:state-machine",
        "default": PREDBAT_MODE_OPTIONS[PREDBAT_MODE_CONTROL_CHARGEDISCHARGE],
        "reset_inverter_force": True,
    },
    {
        "name": "update",
        "friendly_name": "Predbat update",
        "type": "select",
        "options": PREDBAT_UPDATE_OPTIONS,
        "icon": "mdi:state-machine",
        "default": None,
        "restore": False,
        "save": False,
    },
    {
        "name": "manual_charge",
        "friendly_name": "Manual force charge",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "manual": True,
    },
    {
        "name": "manual_export",
        "friendly_name": "Manual force export",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "manual": True,
    },
    {
        "name": "manual_demand",
        "friendly_name": "Manual force demand",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "manual": True,
    },
    {
        "name": "manual_api",
        "friendly_name": "Manual API controls",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "api": True,
    },
    {
        "name": "manual_freeze_charge",
        "friendly_name": "Manual force charge freeze",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "manual": True,
    },
    {
        "name": "manual_freeze_export",
        "friendly_name": "Manual force export freeze",
        "type": "select",
        "options": ["off"],
        "icon": "mdi:state-machine",
        "default": "off",
        "restore": False,
        "manual": True,
    },
    {
        "name": "saverestore",
        "friendly_name": "Save/restore settings",
        "type": "select",
        "options": PREDBAT_SAVE_RESTORE,
        "icon": "mdi:state-machine",
        "default": "",
        "restore": False,
        "save": False,
    },
    {
        "name": "auto_update",
        "friendly_name": "Predbat automatic update enable",
        "type": "switch",
        "default": False,
    },
    {
        "name": "load_filter_modal",
        "friendly_name": "Apply modal filter historical load",
        "type": "switch",
        "enable": "expert_mode",
        "default": True,
    },
    {
        "name": "iboost_enable",
        "friendly_name": "iBoost enable",
        "type": "switch",
        "default": False,
    },
    {
        "name": "carbon_enable",
        "friendly_name": "Carbon enable",
        "type": "switch",
        "default": False,
    },
    {
        "name": "carbon_metric",
        "friendly_name": "Carbon Metric",
        "type": "input_number",
        "min": 0,
        "max": 500,
        "step": 1,
        "unit": "p/Kg",
        "icon": "mdi:molecule-co2",
        "default": 0,
        "enable": "carbon_enable",
    },
    {
        "name": "iboost_solar",
        "friendly_name": "iBoost on solar power",
        "type": "switch",
        "default": True,
        "enable": "iboost_enable",
    },
    {
        "name": "iboost_gas",
        "friendly_name": "iBoost when import electricity cheaper than gas",
        "type": "switch",
        "default": False,
        "enable": "iboost_enable",
    },
    {
        "name": "iboost_gas_export",
        "friendly_name": "iBoost when export electricity cheaper than gas",
        "type": "switch",
        "default": False,
        "enable": "iboost_enable",
    },
    {
        "name": "iboost_charging",
        "friendly_name": "iBoost when battery charging",
        "type": "switch",
        "default": False,
        "enable": "iboost_enable",
    },
    {
        "name": "iboost_rate_threshold",
        "friendly_name": "iBoost max import boost price",
        "type": "input_number",
        "min": -10,
        "max": 100,
        "step": 1,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "iboost_enable",
        "default": 100,
    },
    {
        "name": "iboost_rate_threshold_export",
        "friendly_name": "iBoost max export boost price",
        "type": "input_number",
        "min": -10,
        "max": 100,
        "step": 1,
        "unit": "p/kWh",
        "icon": "mdi:currency-usd",
        "enable": "iboost_enable",
        "default": 100,
    },
    {
        "name": "iboost_smart",
        "friendly_name": "iBoost when import rates are lowest to hit target energy",
        "type": "switch",
        "enable": "iboost_enable",
        "default": False,
    },
    {
        "name": "iboost_smart_min_length",
        "friendly_name": "iBoost smart min length",
        "type": "input_number",
        "min": 30,
        "max": 120,
        "step": 30,
        "unit": "minutes",
        "icon": "mdi:currency-usd",
        "enable": "iboost_enable",
        "default": 30,
    },
    {
        "name": "iboost_on_export",
        "oldname": "iboost_on_export",
        "friendly_name": "iBoost is allowed when battery is force exporting",
        "type": "switch",
        "enable": "iboost_enable",
        "default": False,
    },
    {
        "name": "iboost_prevent_discharge",
        "friendly_name": "When iBoost is active prevent battery discharge",
        "type": "switch",
        "enable": "iboost_enable",
        "default": False,
    },
    {
        "name": "iboost_gas_scale",
        "friendly_name": "iBoost gas price scaling",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.1,
        "unit": "*",
        "icon": "mdi:multiplication",
        "enable": "iboost_enable",
        "default": 1.0,
    },
    {
        "name": "iboost_max_energy",
        "friendly_name": "iBoost max energy",
        "type": "input_number",
        "min": 0,
        "max": 30,
        "step": 0.1,
        "unit": "kWh",
        "enable": "iboost_enable",
        "default": 3.0,
    },
    {
        "name": "iboost_today",
        "friendly_name": "iBoost today",
        "type": "input_number",
        "min": 0,
        "max": 30,
        "step": 0.1,
        "unit": "kWh",
        "enable": "iboost_enable",
        "default": 0.0,
    },
    {
        "name": "iboost_max_power",
        "friendly_name": "iBoost max power",
        "type": "input_number",
        "min": 0,
        "max": 3500,
        "step": 100,
        "unit": "W",
        "enable": "iboost_enable",
        "default": 2400,
    },
    {
        "name": "iboost_min_power",
        "friendly_name": "iBoost min power",
        "type": "input_number",
        "min": 0,
        "max": 3500,
        "step": 100,
        "unit": "W",
        "enable": "iboost_enable",
        "default": 500,
    },
    {
        "name": "iboost_min_soc",
        "friendly_name": "iBoost min soc",
        "type": "input_number",
        "min": 0,
        "max": 100,
        "step": 5,
        "unit": "%",
        "icon": "mdi:percent",
        "enable": "iboost_enable",
        "default": 0.0,
    },
    {
        "name": "iboost_value_scaling",
        "friendly_name": "iBoost value scaling",
        "type": "input_number",
        "min": 0,
        "max": 2.0,
        "step": 0.05,
        "unit": "*",
        "enable": "iboost_enable",
        "icon": "mdi:multiplication",
        "default": 0.75,
    },
    {
        "name": "iboost_energy_subtract",
        "friendly_name": "Subtract iBoost energy from load predictions",
        "type": "switch",
        "enable": "iboost_enable",
        "default": True,
    },
    {
        "name": "holiday_days_left",
        "friendly_name": "Holiday days left",
        "type": "input_number",
        "min": 0,
        "max": 28,
        "step": 1,
        "unit": "days",
        "icon": "mdi:clock-end",
        "default": 0,
        "restore": False,
    },
    {
        "name": "forecast_plan_hours",
        "friendly_name": "Plan forecast hours",
        "type": "input_number",
        "min": 8,
        "max": 96,
        "step": 1,
        "unit": "hours",
        "icon": "mdi:clock-end",
        "enable": "expert_mode",
        "default": 24,
    },
    {
        "name": "plan_debug",
        "friendly_name": "HTML Plan Debug",
        "type": "switch",
        "default": False,
        "enable": "expert_mode",
    },
    {
        "name": "predheat_enable",
        "friendly_name": "Enable PredHeat",
        "type": "switch",
        "default": False,
    },
    {
        "name": "next_volume_temp",
        "friendly_name": "Volume Temperature Next",
        "type": "input_number",
        "min": -20,
        "max": 40,
        "step": 0.1,
        "unit": "c",
        "default": 20,
        "enable": "predheat_enable",
    },
]

# These settings can be overridden by the API
CONFIG_API_OVERRIDE = {
    "inverter_limit": True,
    "export_limit": True,
    "inverter_battery_rate_min": True,
    "inverter_reserve_max": True,
    "battery_rate_max": True,
    "car_charging_soc": True,
    "car_charging_limit": True,
    "car_charging_battery_size": True,
    "days_previous": True,
    "days_previous_weight": True,
    "battery_scaling": True,
    "forecast_hours": True,
    "import_export_scaling": True,
    "inverter_limit_charge": True,
    "inverter_limit_discharge": True,
    "rates_import_override": True,
    "rates_export_override": True,
}

"""
GE Inverters are the default but not all inverters have the same parameters so this constant
maps the parameters that are different between brands.

The approach is to attempt to mimic the GE model with dummy entities in HA so that predbat GE
code can be used with minimal modification.
"""
INVERTER_DEF = {
    "GE": {
        "name": "GivEnergy",
        "has_rest_api": True,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": False,
        "has_charge_enable_time": True,
        "has_discharge_enable_time": False,
        "has_target_soc": True,
        "has_reserve_soc": True,
        "has_timed_pause": True,
        "charge_time_format": "HH:MM:SS",
        "charge_time_entity_is_option": True,
        "soc_units": "kWh",
        "num_load_entities": 1,
        "has_ge_inverter_mode": True,
        "time_button_press": False,
        "clock_time_format": "%H:%M:%S",
        "write_and_poll_sleep": 10,
        "has_time_window": True,
        "support_charge_freeze": True,
        "support_discharge_freeze": True,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "GEC": {
        "name": "GivEnergy Cloud",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": False,
        "has_charge_enable_time": True,
        "has_discharge_enable_time": True,
        "has_target_soc": True,
        "has_reserve_soc": True,
        "has_timed_pause": True,
        "charge_time_format": "HH:MM:SS",
        "charge_time_entity_is_option": True,
        "soc_units": "kWh",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%H:%M:%S",
        "write_and_poll_sleep": 10,
        "has_time_window": True,
        "support_charge_freeze": True,
        "support_discharge_freeze": True,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "GEE": {
        "name": "GivEnergy EMC",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": True,
        "has_reserve_soc": True,
        "has_timed_pause": False,
        "charge_time_format": "HH:MM:SS",
        "charge_time_entity_is_option": True,
        "soc_units": "kWh",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%H:%M:%S",
        "write_and_poll_sleep": 10,
        "has_time_window": True,
        "support_charge_freeze": True,
        "support_discharge_freeze": False,
        "has_idle_time": True,
        "can_span_midnight": False,
        "charge_discharge_with_rate": False,
    },
    "GS": {
        "name": "Ginlong Solis",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "current",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "H M",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 2,
        "has_ge_inverter_mode": False,
        "time_button_press": True,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": True,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": False,
        "charge_discharge_with_rate": False,
    },
    "SE": {
        "name": "SolarEdge",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "SX4": {
        "name": "Solax Gen4 (Modbus Power Control)",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": True,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "SF": {
        "name": "Sofar HYD",
        "has_rest_api": False,
        "has_mqtt_api": True,
        "output_charge_control": "none",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "SFMB": {
        "name": "Sofar HYD",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "none",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "HU": {
        "name": "Huawei Solar",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "power",
        "charge_control_immediate": True,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 4,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "SK": {
        "name": "Sunsynk",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "current",
        "charge_control_immediate": False,
        "current_dp": 0,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": True,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%d %H:%M:%S",
        "write_and_poll_sleep": 5,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": True,
        "charge_discharge_with_rate": False,
    },
    "SA": {
        "name": "Solar Assistant",
        "has_rest_api": False,
        "has_mqtt_api": False,
        "output_charge_control": "none",
        "charge_control_immediate": False,
        "current_dp": 0,
        "has_charge_enable_time": False,
        "has_discharge_enable_time": False,
        "has_target_soc": False,
        "has_reserve_soc": False,
        "has_timed_pause": False,
        "charge_time_format": "S",
        "charge_time_entity_is_option": False,
        "soc_units": "%",
        "num_load_entities": 1,
        "has_ge_inverter_mode": False,
        "time_button_press": False,
        "clock_time_format": "%Y-%m-%dT%H:%M:%S",
        "write_and_poll_sleep": 5,
        "has_time_window": False,
        "support_charge_freeze": False,
        "support_discharge_freeze": False,
        "has_idle_time": False,
        "can_span_midnight": False,
        "charge_discharge_with_rate": False,
    },
}

# Control modes for Solax inverters
SOLAX_SOLIS_MODES = {
    "Selfuse - No Grid Charging": 1,
    "Timed Charge/Discharge - No Grid Charging": 3,
    "Backup/Reserve - No Grid Charging": 17,
    "Selfuse": 33,
    "Timed Charge/Discharge": 35,
    "Off-Grid Mode": 37,
    "Battery Awaken": 41,
    "Battery Awaken + Timed Charge/Discharge": 43,
    "Backup/Reserve - No Timed Charge/Discharge": 49,
    "Backup/Reserve": 51,
    "Feed-in priority - No Grid Charging": 64,
    "Feed-in priority - No Timed Charge/Discharge": 96,
    "Feed-in priority": 98,
}
# New modes are from 2024.03.2 controlled with solax_modbus_new in apps.yaml
SOLAX_SOLIS_MODES_NEW = {
    "Self-Use - No Grid Charging": 1,
    "Timed Charge/Discharge - No Grid Charging": 3,
    "Backup/Reserve - No Grid Charging": 17,
    "Self-Use - No Timed Charge/Discharge": 33,
    "Self-Use": 35,
    "Off-Grid Mode": 37,
    "Battery Awaken": 41,
    "Battery Awaken + Timed Charge/Discharge": 43,
    "Backup/Reserve - No Timed Charge/Discharge": 49,
    "Backup/Reserve": 51,
    "Feed-in priority - No Grid Charging": 64,
    "Feed-in priority - No Timed Charge/Discharge": 96,
    "Feed-in priority": 98,
}

# Apps.yaml validation schema
APPS_SCHEMA = {
    "currency_symbols": {"type": "string|string_list"},
    "db_enable": {"type": "boolean"},
    "db_days": {"type": "integer"},
    "db_mirror_ha": {"type": "boolean"},
    "db_primary": {"type": "boolean"},
    "threads": {"type": "string|integer", "allowed": ["auto", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]},
    "ha_url": {"type": "string", "empty": False},
    "ha_key": {"type": "string", "empty": False},
    "load_filter_threshold": {"type": "integer"},
    "web_port": {"type": "integer"},
    "load_today": {"type": "sensor|sensor_list", "sensor_type": "float", "required": True},
    "import_today": {
        "type": "sensor|sensor_list",
        "sensor_type": "float",
    },
    "export_today": {
        "type": "sensor|sensor_list",
        "sensor_type": "float",
    },
    "pv_today": {
        "type": "sensor|sensor_list",
        "sensor_type": "float",
    },
    "load_forecast_only": {"type": "boolean"},
    "load_forecast": {
        "type": "sensor_list",
        "sensor_type": "dict|list",
    },
    "ge_cloud_data": {"type": "boolean"},
    "ge_cloud_serial": {"type": "string", "empty": False},
    "ge_cloud_key": {"type": "string", "empty": False},
    "ge_cloud_direct": {"type": "boolean"},
    "ge_cloud_automatic": {"type": "boolean"},
    "num_inverters": {"type": "integer", "zero": False},
    "balance_inverters_seconds": {"type": "integer", "zero": True},
    "givtcp_rest": {"type": "string_list", "entries": "num_inverters"},
    "charge_rate": {"type": "sensor_list", "sensor_type": "float", "modify": True, "entries": "num_inverters"},
    "discharge_rate": {"type": "sensor_list", "sensor_type": "float", "modify": True, "entries": "num_inverters"},
    "battery_power": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "pv_power": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "load_power": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "soc_kw": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "soc_max": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "reserve": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "inverter_mode": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "inverter_time": {"type": "sensor_list", "sensor_type": "string", "entries": "num_inverters"},
    "inverter_type": {"type": "string_list", "entries": "num_inverters"},
    "charge_start_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "charge_end_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "charge_limit": {"type": "sensor_list", "sensor_type": "float", "modify": True, "entries": "num_inverters"},
    "scheduled_charge_enable": {"type": "sensor_list", "sensor_type": "boolean", "modify": True, "entries": "num_inverters"},
    "scheduled_discharge_enable": {"type": "sensor_list", "sensor_type": "boolean", "modify": True, "entries": "num_inverters"},
    "discharge_start_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "discharge_end_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "battery_temperature": {"type": "sensor_list", "sensor_type": "float", "entries": "num_inverters"},
    "pause_mode": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "pause_start_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "pause_end_time": {"type": "sensor_list", "sensor_type": "string", "modify": True, "entries": "num_inverters"},
    "inverter_limit": {"type": "sensor_list", "sensor_type": "integer", "modify": False, "zero": False, "entries": "num_inverters"},
    "inverter_limit_charge": {"type": "sensor_list", "sensor_type": "integer", "modify": False, "zero": False, "entries": "num_inverters"},
    "export_limit": {"type": "integer_list", "entries": "num_inverters"},
    "inverter_battery_rate_min": {"type": "integer", "zero": False, "entries": "num_inverters"},
    "inverter_reserve_max": {"type": "integer", "zero": False, "entries": "num_inverters"},
    "battery_charge_power_curve: ": {"type": "int_float_dict"},
    "battery_discharge_power_curve: ": {"type": "int_float_dict"},
    "clock_skew": {"type": "integer"},
    "solcast_api_key": {"type": "string", "empty": False},
    "solcast_host": {"type": "string", "empty": False},
    "solcast_poll_hours": {"type": "float", "zero": False},
    "pv_forecast_today": {"type": "sensor", "sensor_type": "float"},
    "pv_forecast_tomorrow": {"type": "sensor", "sensor_type": "float"},
    "pv_forecast_d3": {"type": "sensor", "sensor_type": "float"},
    "pv_forecast_d4": {"type": "sensor", "sensor_type": "float"},
    "car_charging_energy": {"type": "sensor", "sensor_type": "float"},
    "num_cars": {"type": "integer", "zero": True},
    "car_charging_planned": {"type": "sensor|sensor_list", "sensor_type": "string", "entries": "num_cars"},
    "car_charging_planned_response": {"type": "string_list"},
    "car_charging_now": {"type": "sensor|sensor_list", "sensor_type": "string", "entries": "num_cars"},
    "car_charging_now_response": {"type": "string_list"},
    "car_charging_battery_size": {"type": "sensor", "zero": False, "sensor_type": "float", "entries": "num_cars"},
    "car_charging_soc": {"type": "sensor", "sensor_type": "float", "entries": "num_cars"},
    "car_charging_limit": {"type": "sensor", "sensor_type": "float", "entries": "num_cars"},
    "car_charging_exclusive": {"type": "boolean_list", "entries": "num_cars"},
    "carbon_intensity": {"type": "sensor", "sensor_type": "string"},
    "octopus_intelligent_slot": {"type": "sensor", "sensor_type": "boolean"},
    "octopus_ready_time": {"type": "sensor", "sensor_type": "string"},
    "octopus_charge_limit": {"type": "sensor", "sensor_type": "float"},
    "octopus_slot_low_rate": {"type": "boolean"},
    "octopus_saving_session_octopoints_per_penny": {"type": "integer"},
    "octopus_free_url": {"type": "string", "empty": False},
    "metric_octopus_import": {"type": "sensor", "sensor_type": "float"},
    "metric_octopus_export": {"type": "sensor", "sensor_type": "float"},
    "octopus_api_key": {"type": "string", "empty": False},
    "octopus_api_account": {"type": "string", "empty": False},
    "rates_import": {"type": "dict_list"},
    "rates_export": {"type": "dict_list"},
    "alerts": {"type": "dict"},
    "rates_import_octopus_url": {"type": "string", "empty": False},
    "rates_export_octopus_url": {"type": "string", "empty": False},
    "rates_import_override": {"type": "dict_list"},
    "rates_export_override": {"type": "dict_list"},
    "days_previous": {"type": "integer_list"},
    "days_previous_weight": {"type": "float_list"},
    "forecast_hours": {"type": "integer"},
    "notify_devices": {"type": "string_list"},
    "battery_scaling": {"type": "float_list"},
    "import_export_scaling": {"type": "float"},
    "export_triggers": {"type": "dict_list"},
    "iboost_energy_today": {"type": "sensor", "sensor_type": "float"},
    "metric_octopus_gas": {"type": "sensor", "sensor_type": "float"},
    "rates_gas": {"type": "dict_list"},
    "futurerate_url": {"type": "string", "empty": False},
    "futurerate_adjust_import": {"type": "boolean"},
    "futurerate_adjust_export": {"type": "boolean"},
    "futurerate_peak_start": {"type": "string", "empty": False},
    "futurerate_peak_end": {"type": "string", "empty": False},
    "octopus_region": {"type": "string", "empty": False},
    "compare_list": {"type": "dict_list"},
    "watch_list": {"type": "string_list"},
    "charge_start_service": {"type": "dict_list|string"},
    "charge_stop_service": {"type": "dict_list|string"},
    "discharge_start_service": {"type": "dict_list|string"},
    "discharge_stop_service": {"type": "dict_list|string"},
    "charge_freeze_service": {"type": "dict_list|string"},
    "discharge_freeze_service": {"type": "dict_list|string"},
    "device_id": {"type": "string", "empty": False},
    "predheat": {"type": "dict"},
}
